set up shopify app to build a local optimizely sdk from source
optimizely/mobile-buy-sdk-android pull request #2
Opened 2017-02-15 23:32 UTC by wangjoshuah

2017-02-15 23:43 UTC, mikeproeng37 reviewed
Is the goal of this to make it so that the test app will always build locally as opposed to build from bintray? Is there a reason to skip bintray altogether?

2017-02-15 23:43 UTC, mikeng13 commented on MobileBuy/build.gradle
> +    // keep this here to allow ENV vairables to be set.
typo in `variables`

2017-02-15 23:43 UTC, mikeng13 commented on MobileBuy/sample/shop.properties
> +API_KEY=30e8a770c793382de7516f5fc0a497f1
this shouldn't be checked in

2017-02-15 23:43 UTC, mikeng13 commented on MobileBuy/settings.gradle
> +project(':android-sdk').projectDir = new File('../../android-sdk/android-sdk')
will the android-sdk included in this repo?

2017-02-15 23:45 UTC, jophde approved these changes

2017-02-15 23:45 UTC, jophde commented on MobileBuy/build.gradle
> +    // keep this here to allow ENV vairables to be set.
This really allows the ENV variables to *not* be set.

2017-02-15 23:45 UTC, jophde commented on MobileBuy/build.gradle
> +// snapshot of dependencies to use
This allows the test app to control the versions of the deps that the android sdk is built with without needing to modify code in the android sd repo itself.

2017-02-15 23:47 UTC, jophde commented on MobileBuy/sample/shop.properties
> +API_KEY=30e8a770c793382de7516f5fc0a497f1
Agree with mike, this should be read in from env variable or be git ignored.

2017-02-15 23:47 UTC, jophde requested changes
Shouldn't store API key in source

2017-02-16 00:07 UTC, jophde commented
@mikeng13 building from source locally like this allows the android-sdk be checked out at whatever commit.  It could be checked out at a release tag or at a feature branch.  It could be done with bintray and artifacts but you would need push every feature branch or commit you want to test up as artifact to bintray/maven.

2017-02-16 00:51 UTC, mikeng13 commented
@jophde does this mean that we need to update the android-sdk source here in this repo every time we want to test a new version of the SDK? I don't see where we are adding the android-sdk source code to this repo

2017-02-16 01:05 UTC, jophde commented
We aren't adding to the repo.  You just to clone this repo and `android-sdk` in the same directory.

2017-02-16 01:34 UTC, mikeng13 commented
Ah got it. #nooquestions

2017-02-16 22:25 UTC, jophde approved these changes

2017-02-17 17:39 UTC, merged